import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <>
  <meta charSet="utf-8" />
  <meta httpEquiv="x-ua-compatible" content="ie=edge" />
  <title>Anish Joshi </title>
  <meta name="author" content="Donat" />
  <meta name="description" content="Donat - Charity & Donation HTML Template" />
  <meta name="keywords" content="Donat - Charity & Donation HTML Template" />
  <meta name="robots" content="INDEX,FOLLOW" />
  {/* Mobile Specific Metas */}
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />
  {/* Favicons - Place favicon.ico in the root directory */}
  <link
    rel="apple-touch-icon"
    sizes="57x57"
    href="assets/img/favicons/apple-icon-57x57.png"
  />
  <link
    rel="apple-touch-icon"
    sizes="60x60"
    href="assets/img/favicons/apple-icon-60x60.png"
  />
  <link
    rel="apple-touch-icon"
    sizes="72x72"
    href="assets/img/favicons/apple-icon-72x72.png"
  />
  <link
    rel="apple-touch-icon"
    sizes="76x76"
    href="assets/img/favicons/apple-icon-76x76.png"
  />
  <link
    rel="apple-touch-icon"
    sizes="114x114"
    href="assets/img/favicons/apple-icon-114x114.png"
  />
  <link
    rel="apple-touch-icon"
    sizes="120x120"
    href="assets/img/favicons/apple-icon-120x120.png"
  />
  <link
    rel="apple-touch-icon"
    sizes="144x144"
    href="assets/img/favicons/apple-icon-144x144.png"
  />
  <link
    rel="apple-touch-icon"
    sizes="152x152"
    href="assets/img/favicons/apple-icon-152x152.png"
  />
  <link
    rel="apple-touch-icon"
    sizes="180x180"
    href="assets/img/favicons/apple-icon-180x180.png"
  />
  <link
    rel="icon"
    type="image/png"
    sizes="192x192"
    href="assets/img/favicons/android-icon-192x192.png"
  />
  <link
    rel="icon"
    type="image/png"
    sizes="32x32"
    href="assets/img/favicons/favicon-32x32.png"
  />
  <link
    rel="icon"
    type="image/png"
    sizes="96x96"
    href="assets/img/favicons/favicon-96x96.png"
  />
  <link
    rel="icon"
    type="image/png"
    sizes="16x16"
    href="assets/img/favicons/favicon-16x16.png"
  />
  <link rel="manifest" href="assets/img/favicons/manifest.json" />
  <meta name="msapplication-TileColor" content="#ffffff" />
  <meta
    name="msapplication-TileImage"
    content="assets/img/favicons/ms-icon-144x144.png"
  />
  <meta name="theme-color" content="#ffffff" />
  {/*==============================
	  Google Fonts
	============================== */}
  <link rel="preconnect" href="https://fonts.googleapis.com/" />
  <link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin="" />
  <link
    href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"
    rel="stylesheet"
  />
  {/*==============================
	    All CSS File
	============================== */}
  {/* Bootstrap */}
  <link rel="stylesheet" href="assets/css/bootstrap.min.css" />
  {/* Fontawesome Icon */}
  <link rel="stylesheet" href="assets/css/fontawesome.min.css" />
  {/* Magnific Popup */}
  <link rel="stylesheet" href="assets/css/magnific-popup.min.css" />
  {/* Swiper Js */}
  <link rel="stylesheet" href="assets/css/swiper-bundle.min.css" />
  {/* Theme Custom CSS */}
  <link rel="stylesheet" href="assets/css/style.css" />
</>

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}





        <Script src="/assets/js/vendor/jquery-3.7.1.min.js" />
        <Script src="assets/js/swiper-bundle.min.js" />
        <Script src="assets/js/bootstrap.min.js" />
        <Script src="assets/js/jquery.magnific-popup.min.js" />
        <Script src="assets/js/jquery.counterup.min.js" />
        <Script src="assets/js/jquery-ui.min.js" />
        <Script src="assets/js/imagesloaded.pkgd.min.js" />
        <Script src="assets/js/isotope.pkgd.min.js" />
        <Script src="assets/js/main.js" />
      </body>
    </html>
  );
}
